#!/usr/bin/env python3
"""
cat_buddy.py — Your terminal cat colony
Pure Python stdlib. No pip installs. Runs in a tmux split pane.

QUICK START:
  # In your main terminal, split a bottom pane:
  tmux split-window -v -l 22 'python3 /path/to/cat_buddy.py'

  # Or just run directly in any terminal:
  python3 cat_buddy.py

CONTROLS:
   Click the bell  → summon a cat (up to 4 at once, pick & name them)
  Click a cat        → open pixel-style interaction menu
  Click  or     → fix a knocked-over plant
  Ctrl+C             → goodbye

CATS:  Séraphine · Hazel · Kulfi · Nyx · Arwen · Saffron · Mochi · Oreo
"""

import sys, os, tty, termios, select, signal, time, random, re, textwrap, json, atexit
from datetime import datetime
from pathlib import Path

# Import pre-converted pixel art sprites (generated by convert_assets.py)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sprite_data

# ══════════════════════════════════════════════════════════════════════════════
# § 1  ANSI / TERMINAL HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def fg(r, g, b):  return f'\033[38;2;{r};{g};{b}m'
def bg(r, g, b):  return f'\033[48;2;{r};{g};{b}m'
RST   = '\033[0m'
BOLD  = '\033[1m'
DIM   = '\033[2m'
HIDE  = '\033[?25l'
SHOW  = '\033[?25h'
MON   = '\033[?1000h\033[?1006h'   # SGR mouse on
MOFF  = '\033[?1000l\033[?1006l'

def goto(r, c): return f'\033[{r};{c}H'

def term_size():
    import shutil
    s = shutil.get_terminal_size((120, 24))
    return s.lines, s.columns

# ══════════════════════════════════════════════════════════════════════════════
# § 1.5  CONFIG / STATE / SOUND
# ══════════════════════════════════════════════════════════════════════════════
#
# Config file:  ~/.config/cozy-cats/config.json  (or $XDG_CONFIG_HOME/cozy-cats/)
#   {
#     "sound": true,
#     "fps":   12,
#     "cats":  { "mochi": { "water_min": 12, "messages": {"motiv": ["..."]} } },
#     "palettes": { "kulfi": { "F": [245,145,32] } },
#     "scene": { "bell_px": 28, "bell_py": 2 }
#   }
# State file:   ~/.config/cozy-cats/state.json   (colony persistence — who was summoned)

CFG_DIR = Path(os.environ.get('XDG_CONFIG_HOME') or (Path.home() / '.config')) / 'cozy-cats'
CONFIG_FILE = CFG_DIR / 'config.json'
STATE_FILE  = CFG_DIR / 'state.json'

SOUND_ON        = True
CONFIGURED_FPS  = 12
SCENE_OVERRIDES = {}   # populated by apply_config


def load_config():
    try:
        if CONFIG_FILE.exists():
            return json.loads(CONFIG_FILE.read_text())
    except Exception:
        pass
    return {}


def write_default_config():
    """Drop a commented example config on first run so users know it exists."""
    if CONFIG_FILE.exists():
        return
    try:
        CFG_DIR.mkdir(parents=True, exist_ok=True)
        default = {
            "_comment": "cozy-cats config. Edit and save, then relaunch. Keys starting with _ are ignored.",
            "sound": True,
            "fps": 12,
            "cats": {
                "_example": {
                    "_note": "Per-cat overrides. Valid cat keys: seraphine, hazel, kulfi, nyx, arwen, saffron, mochi, oreo",
                    "water_min": 30,
                    "break_min": 60,
                    "motiv_min": 15,
                    "messages": {
                        "motiv": ["Extra motivational line appended to the pool."]
                    }
                }
            },
            "palettes": {
                "_example": {
                    "_note": "Per-cat RGB overrides. Keys: O=outline, F=fur, B=belly, V=eye, N=nose, W=whisker",
                    "F": [245, 145, 32]
                }
            },
            "scene": {
                "_note": "Override pixel positions. Available: bell_px, bell_py, tower_px, desk_px, chair_px, lamp_px, shelf_px, bed_px, plant1_px, plant2_px, keyboard_px"
            }
        }
        CONFIG_FILE.write_text(json.dumps(default, indent=2))
    except Exception:
        pass


def apply_config(cfg):
    """Apply config dict to module-level state + DEFS/PALETTES in place."""
    global SOUND_ON, CONFIGURED_FPS, SCENE_OVERRIDES
    if 'sound' in cfg:
        SOUND_ON = bool(cfg['sound'])
    if 'fps' in cfg:
        try:
            CONFIGURED_FPS = max(1, min(60, int(cfg['fps'])))
        except Exception:
            pass
    # Per-cat overrides
    tunable = ('water_min','break_min','motiv_min',
               'flee_chance','knock_chance','hide_chance',
               'beg_chance','chirp_chance')
    for key, over in (cfg.get('cats') or {}).items():
        if key.startswith('_') or key not in DEFS:
            continue
        if not isinstance(over, dict):
            continue
        for field in tunable:
            if field in over:
                DEFS[key][field] = over[field]
        for cat_msg, lines in (over.get('messages') or {}).items():
            if isinstance(lines, list):
                DEFS[key]['msg'].setdefault(cat_msg, []).extend(
                    [str(l) for l in lines]
                )
    # Scene overrides — stored for Scene.__init__ to consume
    scene_cfg = cfg.get('scene') or {}
    SCENE_OVERRIDES = {k: v for k, v in scene_cfg.items() if not k.startswith('_')}


def load_state():
    """Return list of {'key','name'} entries from last session."""
    try:
        if STATE_FILE.exists():
            data = json.loads(STATE_FILE.read_text())
            return data.get('cats') or []
    except Exception:
        pass
    return []


def save_state(cats):
    try:
        CFG_DIR.mkdir(parents=True, exist_ok=True)
        STATE_FILE.write_text(json.dumps({
            "cats": [{"key": c.key, "name": c.name} for c in cats]
        }, indent=2))
    except Exception:
        pass


def reset_state():
    try:
        if STATE_FILE.exists():
            STATE_FILE.unlink()
    except Exception:
        pass


def beep():
    """Terminal bell (BEL) — silent no-op if SOUND_ON is False."""
    if SOUND_ON:
        try:
            sys.stdout.write('\a')
            sys.stdout.flush()
        except Exception:
            pass


def _emergency_restore():
    """atexit hook: restore terminal if we crash hard without running cleanup."""
    try:
        sys.stdout.write('\033[?1000l\033[?1006l\033[?25h\033[0m')
        sys.stdout.flush()
    except Exception:
        pass

atexit.register(_emergency_restore)

# ══════════════════════════════════════════════════════════════════════════════
# § 2  INPUT HANDLING  (non-blocking, mouse + keyboard)
# ══════════════════════════════════════════════════════════════════════════════

_MOUSE_RE = re.compile(r'\x1b\[<(\d+);(\d+);(\d+)([Mm])')

def read_events():
    """Returns list of event dicts. Non-blocking."""
    if not select.select([sys.stdin], [], [], 0)[0]:
        return []
    raw = b''
    while select.select([sys.stdin], [], [], 0)[0]:
        chunk = os.read(sys.stdin.fileno(), 256)
        if not chunk:
            break
        raw += chunk
    buf = raw.decode('utf-8', errors='replace')
    events = []
    # Mouse
    for m in _MOUSE_RE.finditer(buf):
        btn, col, row, act = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4)
        if act == 'M' and btn == 0:
            events.append({'t': 'click', 'col': col, 'row': row})
    buf = _MOUSE_RE.sub('', buf)
    # Keyboard (after stripping mouse)
    i = 0
    while i < len(buf):
        ch = buf[i]
        if ch == '\x03':
            events.append({'t': 'quit'})
        elif ch == '\x1b' and i + 2 < len(buf):
            seq = buf[i:i+3]
            if   seq == '\x1b[A': events.append({'t': 'key', 'k': 'UP'});    i += 3; continue
            elif seq == '\x1b[B': events.append({'t': 'key', 'k': 'DOWN'});  i += 3; continue
            else:                 events.append({'t': 'esc'})
        elif ch in ('\r', '\n'):
            events.append({'t': 'key', 'k': 'ENTER'})
        elif ch == '\x7f':
            events.append({'t': 'key', 'k': 'BACKSPACE'})
        elif ch.isprintable():
            events.append({'t': 'key', 'k': ch})
        i += 1
    return events

# ══════════════════════════════════════════════════════════════════════════════
# § 3  PIXEL CANVAS  (▀ half-block + Kitty graphics renderers)
# ══════════════════════════════════════════════════════════════════════════════

SCENE_BG = (138, 122, 158)  # lavender room colour
FLOOR_H  = 6              # base floor height in pixels (scaled in Kitty mode)

def is_kitty():
    """Detect Kitty terminal with graphics protocol support.
    Returns False inside tmux because tmux strips Kitty graphics sequences."""
    if os.environ.get('TMUX'):
        return False
    return os.environ.get('TERM_PROGRAM', '').lower() == 'kitty'


class Canvas:
    """
    Pixel framebuffer with two rendering modes:

    scale=1 (half-block): pw = term_w, ph = term_h * 2
        Each terminal cell shows 2 vertical pixels via the ▀ character.
        Resolution at 22 rows x 120 cols = 120 x 44 pixels.

    scale=2 (Kitty graphics): pw = term_w * 2, ph = term_h * 4
        Each terminal cell maps to a 2x4 pixel region. The Kitty
        graphics protocol renders the framebuffer as a native image,
        giving 4x the pixel count without character approximation.
        Resolution at 22 rows x 120 cols = 240 x 88 pixels.
    """
    def __init__(self, term_h, term_w, scale=1):
        self.th, self.tw = term_h, term_w
        self.scale = scale
        self.ph = term_h * 2 * scale   # pixel height
        self.pw = term_w * scale        # pixel width
        self._b = [[None]*self.pw for _ in range(self.ph)]

    def fill(self, color=None):
        c = color or SCENE_BG
        for row in self._b:
            for i in range(self.pw): row[i] = c

    def put(self, py, px, color):
        if 0 <= py < self.ph and 0 <= px < self.pw:
            self._b[py][px] = color

    def rect(self, py, px, h, w, color):
        for dy in range(h):
            for dx in range(w): self.put(py+dy, px+dx, color)

    def blit(self, py, px, sprite):
        """Stamp pixel sprite (list of rows of colour|None) at (py,px)."""
        for dr, row in enumerate(sprite):
            for dc, c in enumerate(row):
                if c is not None: self.put(py+dr, px+dc, c)

    def render(self, start_row=1):
        """Convert to ANSI string. Uses ▀ half-blocks (scale=1 fallback)."""
        SBG = SCENE_BG
        rows = self._b
        if self.ph % 2:
            rows = rows + [[None]*self.pw]
        parts = [HIDE]
        for i in range(0, len(rows), 2):
            tr = start_row + i // 2
            top_r, bot_r = rows[i], rows[i+1]
            parts.append(f'\033[{tr};1H')
            parts.append(bg(*SBG))
            for t, b in zip(top_r, bot_r):
                t = t or SBG
                b = b or SBG
                if t == b:
                    parts.append(bg(*t) + ' ')
                else:
                    parts.append(bg(*b) + fg(*t) + '▀')
            parts.append(RST)
        return ''.join(parts)

    def render_kitty(self, start_row=1):
        """Render canvas as a Kitty graphics protocol image.

        Sends zlib-compressed RGB data; Kitty scales it to fit the
        terminal cell grid (c x r cells). Much higher quality than
        half-block characters, especially for pixel art.
        """
        import base64, zlib
        SBG = SCENE_BG
        # Build RGB byte array
        buf = bytearray(self.ph * self.pw * 3)
        idx = 0
        for row in self._b:
            for c in row:
                r, g, b = c or SBG
                buf[idx] = r; buf[idx+1] = g; buf[idx+2] = b
                idx += 3

        compressed = zlib.compress(bytes(buf), 1)
        data = base64.standard_b64encode(compressed).decode('ascii')

        parts = [HIDE, f'\033[{start_row};1H']

        CHUNK = 4096
        header = f'a=T,f=24,o=z,s={self.pw},v={self.ph},c={self.tw},r={self.th},i=1,q=2'

        if len(data) <= CHUNK:
            parts.append(f'\033_G{header};{data}\033\\')
        else:
            chunks = [data[i:i+CHUNK] for i in range(0, len(data), CHUNK)]
            parts.append(f'\033_G{header},m=1;{chunks[0]}\033\\')
            for chunk in chunks[1:-1]:
                parts.append(f'\033_Gm=1;{chunk}\033\\')
            parts.append(f'\033_Gm=0;{chunks[-1]}\033\\')

        return ''.join(parts)

# ══════════════════════════════════════════════════════════════════════════════
# § 4  CAT SPRITES  (loaded from sprite_data.py — 16×16 pixel art)
# ══════════════════════════════════════════════════════════════════════════════

# ── Runtime sprite downscaling ──────────────────────────────────────────────
# When the canvas is small (<=24 terminal rows), sprites are halved so the
# scene fits comfortably. Each 2×2 block is reduced to 1 pixel by picking the
# top-left non-transparent pixel.

COMPACT = False   # set True in run() when pane is small

def _downscale(sprite):
    """Halve a sprite: every 2×2 block -> 1 pixel (nearest-neighbor)."""
    if not sprite:
        return sprite
    h = len(sprite)
    w = len(sprite[0]) if sprite else 0
    out = []
    for y in range(0, h - 1, 2):
        row = []
        for x in range(0, w - 1, 2):
            # Pick first non-None pixel from the 2×2 block
            c = (sprite[y][x] or sprite[y][x+1]
                 or sprite[y+1][x] or sprite[y+1][x+1])
            row.append(c)
        out.append(row)
    return out

# Cache to avoid re-downscaling every frame
_ds_cache = {}

def ds(sprite, key=None):
    """Return downscaled sprite if COMPACT mode, else original."""
    if not COMPACT or not sprite:
        return sprite
    if key and key in _ds_cache:
        return _ds_cache[key]
    result = _downscale(sprite)
    if key:
        _ds_cache[key] = result
    return result

def ds_size(w, h):
    """Return downscaled dimensions if COMPACT mode."""
    if not COMPACT:
        return w, h
    return w // 2, h // 2

# ══════════════════════════════════════════════════════════════════════════════
# § 5  CAT PERSONALITIES & MESSAGES
# ══════════════════════════════════════════════════════════════════════════════

DEFS = {
    'seraphine': {
        'label': 'Séraphine', 'emoji': '', 'key': 'seraphine',
        'food_pref': 'fish', 'food_refuses': ['dry','wet'],
        'water_min': 20, 'break_min': 60, 'motiv_min': 22,
        'msg': {
            'water':   ["Darling. Water. Now.","Your skin. Drink.","Hydration is non-negotiable.","Do I have to tell you again?"],
            'stretch': ["Posture. You look like a goblin. Stand up.","Five minutes. Walk. Come back civilised.","The slouching. Please."],
            'motiv':   ["You're doing adequately.","I suppose that's progress.","Not terrible. Carry on.","I've seen worse. (That's a compliment.)","Excellence takes time."],
            'food_love':  ["Finally. You understand me.","*sniffs elegantly* ...acceptable.","Oh. You remembered. I'm almost impressed."],
            'food_meh':   ["Dry food. Really. How pedestrian.","Remove this immediately.","I don't do that."],
            'pet':        ["*tolerates petting for exactly 3 seconds*","Mmph. You may continue. Briefly.","*slow blink* Fine."],
            'yarn':       ["*bats it away and walks off*","I'm above this."],
            'toy':        ["*watches with supreme disinterest*","Move it faster. No. Slower. Ugh."],
            'fish':       ["Now we're speaking the same language.","*delicate nibbles with great urgency*","I'll accept this."],
            'cuddle':     ["I'll allow it. This once.","*purrs but maintains eye contact to assert dominance*","Do not tell anyone."],
            'wet':        ["I suppose.","Not my preference but fine."],
            'dry':        ["Remove this immediately.","I don't do that."],
            'food_remind':["It's mealtime. For both of us.","You should eat something. Properly.","Have you eaten? I have standards for you."],
            'snack_remind':["A small snack. Something elegant.","Afternoon nibble. You deserve it.","Even I take tea. Eat something."],
        }
    },
    'hazel': {
        'label': 'Hazel', 'emoji': '🟤', 'key': 'hazel',
        'food_pref': 'wet', 'food_refuses': [],
        'water_min': 20, 'break_min': 60, 'motiv_min': 28,
        'flee_chance': 0.18,
        'msg': {
            'water':   ["oh! um... water? if that's okay...","s-sorry to bother you... drink some water? ","water reminder... only if you want..."],
            'stretch': ["maybe... a little break? only if you want ","you've been working so hard... rest a bit?","um, stretching is good... i think..."],
            'motiv':   ["you're doing so well... really... ","i believe in you","it's okay if it's hard. you're still trying.","every little bit of progress counts..."],
            'food_love':  ["*purrs very quietly*","oh... thank you... ","*eats softly and hides face*"],
            'pet':        ["*leans in slowly then startles*","*soft little purr*","oh... okay... ","*closes eyes happily*"],
            'overwhelmed':["oh! sorry, i... i need a moment...","*scurries away quietly*","t-too much... sorry..."],
            'yarn':       ["*bats it gently and looks up to check you're okay*","*plays softly then hides*"],
            'toy':        ["*chases it cautiously*","*pounces then looks embarrassed*"],
            'cuddle':     ["*curls up very small*","oh... okay...  *purrs*"],
            'fish':       ["oh! my favourite...  thank you","*eats happily but quietly*"],
            'dry':        ["*eats quietly*","okay... thank you"],
            'wet':        ["oh! this is wonderful ","*purrs while eating*"],
            'food_remind':["um... have you eaten? please eat...","maybe a little lunch? or dinner?"],
            'snack_remind':["a snack maybe? only if you want...","something small? i worry..."],
        }
    },
    'kulfi': {
        'label': 'Kulfi', 'emoji': '🟠', 'key': 'kulfi',
        'food_pref': 'anything', 'food_refuses': [],
        'water_min': 20, 'break_min': 60, 'motiv_min': 9,
        'knock_chance': 0.0006,
        'msg': {
            'water':   ["WATER. NOW. I ALSO WANT WATER.","drink water or i knock something over","HYDRATION STATION LETS GOOOO ","did you know if you don't drink water you DIE"],
            'stretch': ["ZOOOMIES. you should also move.","GET UP. MOVE. LIKE ME. ALWAYS.","BREAK TIME. I DECLARE IT."],
            'motiv':   ["YOU'RE DOING AMAZINGGGG ","LETS GOOOOO","chaos and code, that's the vibe!!!","BUGS? DESTROY THEM. like i destroy things.","you got this!!!! probably!!!!"],
            'food_love':  ["FINALLY OMG NOM NOM NOM NOM","*inhales meal in 0.3 seconds*","MORE. ALWAYS MORE.","yes yes yes yes yes"],
            'pet':        ["*purrs so hard they vibrate*","LOVE ATTACK.","*bites you affectionately and too hard*","*knocks something while headbutting*"],
            'yarn':       ["I HAVE DESTROYED THE YARN","*yeets the yarn across the room*","YARN?? YARN!!!! *chaos*"],
            'toy':        ["I AM THE APEX PREDATOR","*catches it, kills it, stares at you*","AGAIN. AGAIN. AGAIN.","*leaps directly at your face*"],
            'knock':      ["*CRASH*","oops. (not sorry)","*looks at you while pushing it*","gravity. am i right."],
            'cuddle':     ["*immediately starts purring and kneading*","CUDDLE????? YES.","*pins you down lovingly*"],
            'fish':       ["FISH FISH FISH YES FISH","*inhales it instantly*"],
            'dry':        ["FOOD FOOD FOOD","*crunches aggressively*"],
            'wet':        ["AMAZING. MORE PLEASE.","*eats before bowl hits the floor*"],
            'food_remind':["EAT SOMETHING. I AM ALSO HUNGRY.","FOOD TIME!!!! FOR YOU AND ME!!!!"],
            'snack_remind':["SNACK O'CLOCK!!!","it's snack time and that's MANDATORY"],
        }
    },
    'nyx': {
        'label': 'Nyx', 'emoji': '', 'key': 'nyx',
        'food_pref': 'wet', 'food_refuses': [],
        'water_min': 20, 'break_min': 60, 'motiv_min': 32,
        'hide_chance': 0.0005,
        'msg': {
            'water':   ["...drink water.","*stares from shadow* ...hydrate.","the void reminds you to drink.","...drink. now."],
            'stretch': ["...stretch.","*materialises behind you* take a break.","the dark demands rest."],
            'motiv':   ["...you're doing fine. probably.","the void sees your effort. it approves.","*blinks slowly from darkness*","...keep going.","chaos is productive sometimes."],
            'appear':  ["*manifests from darkness*","*two eyes blink into existence*","*gradually becomes visible*"],
            'disappear':["*fades into shadow*","*the eyes blink once and vanish*","*simply ceases to be visible*"],
            'pet':     ["*leans into hand from darkness*","*purrs at a frequency you can feel but not hear*","...acceptable.","*headbutts and disappears immediately*"],
            'yarn':    ["*stalks the yarn from the shadows*","*bats once then vanishes*"],
            'toy':     ["*bats from concealment*","*the toy disappears. so does nyx.*"],
            'cuddle':  ["...fine.","*warm presence in the dark*","*purrs imperceptibly*"],
            'fish':    ["...yes.","*eats in the shadows*"],
            'dry':     ["*eats silently*"],
            'wet':     ["...acceptable.","*eats methodically*"],
            'food_remind':["...eat.","the void demands you nourish yourself."],
            'snack_remind':["...a snack. from the shadows.","sustenance. now."],
        }
    },
    'arwen': {
        'label': 'Arwen', 'emoji': '', 'key': 'arwen',
        'food_pref': 'dry', 'food_refuses': [],
        'water_min': 20, 'break_min': 60, 'motiv_min': 38,
        'msg': {
            'water':   ["Drink your water. I'm not asking twice.","Hydration. Are we doing this or not.","You look dehydrated. Fix that."],
            'stretch': ["Get up. Walk. I'll be here when you get back.","Take a break. I'm sure you'll survive.","Fine. Rest. Don't make it a whole thing."],
            'motiv':   ["You're fine. Stop doubting yourself.","Was that so hard. Carry on.","Mm. Adequate.","I've seen you do harder things.","Do I look worried? Carry on."],
            'pet':     ["*allows exactly one head scratch*","*leans in, then walks away mid-pet*","...fine. brief contact. approved.","*sits just out of reach then scoots closer*"],
            'ignore':  ["*deliberately turns away*","not right now.","*blinks slowly and looks elsewhere*"],
            'yarn':    ["*bats it once with enormous dignity*","If you insist. *one bat*"],
            'toy':     ["*watches it. does not chase it.*","I see what you're doing."],
            'cuddle':  ["Fine. This is fine.","*purrs minimally*","Don't read into this."],
            'fish':    ["Acceptable.","I prefer dry but I'll eat this."],
            'dry':     ["*purrs faintly while eating*","Now we're talking."],
            'wet':     ["It's fine.","Not my preference."],
            'food_remind':["Eat something. Don't make me ask twice.","Time to eat. Go."],
            'snack_remind':["Have a snack. You've earned it. Probably.","Afternoon snack. Go on."],
        }
    },
    'saffron': {
        'label': 'Saffron', 'emoji': '', 'key': 'saffron',
        'food_pref': 'wet', 'food_refuses': [],
        'water_min': 20, 'break_min': 60, 'motiv_min': 15,
        'chirp_chance': 0.0004,
        'msg': {
            'water':   ["chirp! water time! ","*chirps softly* psst. drink something~","trill~ have you had water lately?"],
            'stretch': ["*chirps twice* stretch break! ","trill! stand up a little!","*soft chirp* you've been sitting a while~"],
            'motiv':   ["*happy chirp* you've got this! ","trill~ look how much you've done!","*chirps warmly* proud of you~","you're doing wonderfully "],
            'chirp':   ["chirp!","trill~","*mrrp*","prrrp?","*soft trill*"],
            'pet':     ["*trills with full-body happiness*","mrrp~ ","*chirps and headbutts softly*","*makes biscuits immediately*"],
            'yarn':    ["*chirps at yarn and gently bats*","trill~ *plays very politely*","*chirp chirp* "],
            'toy':     ["*chirps and pounces with delight*","*trills and bats happily*"],
            'cuddle':  ["*trilling purr* ","*curls up perfectly*","mrrp~ "],
            'fish':    ["*excited chirping*","trill! trill! thank you~"],
            'dry':     ["*chirps contentedly*","trill~ thank you "],
            'wet':     ["*happy chirps*","mrrp~ my favourite! "],
            'food_remind':["chirp! mealtime! go eat~","*trills* food time for you!"],
            'snack_remind':["trill~ snack break!","*chirps* afternoon snack time~"],
        }
    },
    'mochi': {
        'label': 'Mochi', 'emoji': '', 'key': 'mochi',
        'food_pref': 'wet', 'food_refuses': [],
        'water_min': 20, 'break_min': 60, 'motiv_min': 7,
        'beg_chance': 0.0007,
        'msg': {
            'water':   ["HAVE YOU HAD WATER?? please say yes ","water water water water ","bestie. BESTIE. water. please.","i'm so worried about your hydration ","if you don't drink water i'll be sad. forever."],
            'stretch': ["BREAK TIME come sit with me ","please take a break i miss you so much","five minutes. please. i'll be so grateful.","stretch!! and then pet me please!!!"],
            'motiv':   ["you are literally the most amazing person ","i believe in you SO MUCH","you're doing SO GOOD and i love you","keep going!!! i'm cheering for you!!!! ","bestie you are BUILT for this"],
            'attention_seek':["*sits directly on your keyboard*","*walks back and forth in front of screen*","heyyy. hey. HEY. hi. look at me.","*meows loudly for no reason*"],
            'pet':     ["*immediately rolls over for belly rubs*","FINALLY. love me. please.","*grabs your hand so you can't stop*","*purrs at maximum volume*","*makes biscuits on your arm*"],
            'yarn':    ["*attacks yarn like it insulted you*","I WILL PROTECT YOU FROM THE YARN"],
            'toy':     ["AGAIN AGAIN AGAIN AGAIN","*catches it and brings it back for more*"],
            'cuddle':  ["YES. THIS IS WHAT I WANT. ALWAYS.","*immediately falls asleep on you*","you feel that? that's happiness. mine."],
            'fish':    ["FISH?? FOR ME?? I LOVE YOU","*eats while maintaining grateful eye contact*"],
            'dry':     ["*eats happily* thank you thank you","I LOVE FOOD I LOVE YOU"],
            'wet':     ["MY FAVOURITE!! YOU REMEMBERED!!","*purrs so loud it echoes*"],
            'food_remind':["EAT SOMETHING BESTIE PLEASE","have you eaten?? i'm worried!!"],
            'snack_remind':["SNACK TIME!! treat yourself!!","afternoon snack!! you deserve it!!"],
        }
    },
    'oreo': {
        'label': 'Oreo', 'emoji': '', 'key': 'oreo',
        'food_pref': 'anything', 'food_refuses': [],
        'water_min': 20, 'break_min': 60, 'motiv_min': 19,
        'beg_chance': 0.0009,
        'knock_chance': 0.0004,
        'msg': {
            'water':   ["water time. also food time? food time.","drink water. then give me food. deal.","HYDRATION. also FOOD. mostly food."],
            'stretch': ["get up. stretch. feed me on the way back.","break time. bring snacks for me.","walk around. i'll follow you hoping for food."],
            'motiv':   ["you're doing great. now feed me.","incredible work. snack? for me?","wow amazing. food?","you're a genius. a genius who should feed me."],
            'beg':     ["*stares at you with maximum intensity*","food? food. food!! FOOD.","*sits directly in front of you*","i'm starving. (i'm not starving. feed me anyway.)","*places paw on your hand meaningfully*"],
            'eat':     ["*inhales food without tasting it*","NOM NOM NOM... more?","*eats your food too, given the chance*","already gone. was good though."],
            'pet':     ["*headbutts hand then looks for food*","thanks. food now?","*purrs and checks your pocket for snacks*"],
            'yarn':    ["*eats the yarn*","is this edible? finding out."],
            'toy':     ["*catches it, drops it, stares at you expectantly*","*bats it once then looks at food bowl*"],
            'cuddle':  ["*cuddles then tries to sneak food*","okay but ALSO food?"],
            'fish':    ["FISH","*inhales entire fish*","already gone."],
            'dry':     ["*crunches aggressively*","NOM. more?"],
            'wet':     ["*inhales before bowl hits floor*","MORE."],
            'knock':   ["*CRASH*","oops. (not sorry)","*looks at you while pushing it*"],
            'food_remind':["FOOD. for you. and also me.","eat something. then feed me."],
            'snack_remind':["snack time. for you. AND me.","afternoon snack. i'll have some too."],
        }
    },
}

ALL_CAT_KEYS = ['seraphine','hazel','kulfi','nyx','arwen','saffron','mochi','oreo']

# ══════════════════════════════════════════════════════════════════════════════
# § 6  SCENE FURNITURE  (sprite_data-based room rendering)
# ══════════════════════════════════════════════════════════════════════════════
#
# All coordinates are in pixel space (py=pixel-row, px=pixel-col).
# 1 terminal row = 2 pixel rows.  1 terminal col = 1 pixel col.
#
# Room sprites are loaded from sprite_data at draw time via cv.blit().
# Plants can be knocked over by Kulfi and Oreo.

WALL_HI  = (148, 132, 168)
WALL_LO  = (128, 112, 148)
FL_A     = (138, 98, 62)
FL_B     = (124, 88, 55)
FL_BOARD = (108, 74, 46)

BELL_GOLD = (222, 172, 38)

# Default plants for the scene (user can override in config)
DEFAULT_PLANTS = ['orchid_pot', 'parlor_palm']


def draw_background(cv):
    ph, pw = cv.ph, cv.pw
    s = cv.scale
    floor_h = FLOOR_H * s
    board_h = 2 * s
    floor_top = ph - floor_h
    for py in range(floor_top):
        t = py / max(1, floor_top)
        shade = tuple(int(WALL_HI[i] + (WALL_LO[i]-WALL_HI[i])*t) for i in range(3))
        for px in range(pw):
            cv.put(py, px, shade)
    for py in range(floor_top, ph):
        for px in range(pw):
            col = FL_A if ((px//6 + py//4) % 2 == 0) else FL_B
            cv.put(py, px, col)
    for py in range(floor_top, floor_top + board_h):
        for px in range(pw):
            cv.put(py, px, FL_BOARD)


def draw_sprite(cv, px, py, sprite_name, get_fn=None):
    """Blit a named sprite from sprite_data onto the canvas (downscaled if COMPACT)."""
    fn = get_fn or sprite_data.get_room_sprite
    sp = fn(sprite_name)
    if sp:
        sp = ds(sp, f'room_{sprite_name}')
        cv.blit(py, px, sp)


def draw_plant(cv, px, py, plant_name, knocked=False):
    """Draw a plant, optionally knocked over (shifted + scattered)."""
    sp = sprite_data.get_plant_sprite(plant_name)
    if not sp:
        return
    sp = ds(sp, f'plant_{plant_name}')
    if knocked:
        pw_p = len(sp[0]) if sp else 8
        ph_p = len(sp)
        for dr, row in enumerate(sp):
            for dc, c in enumerate(row):
                if c is not None:
                    cv.put(py + ph_p - 4 + dc % 6, px - 6 + dr, c)
        return
    cv.blit(py, px, sp)

# ══════════════════════════════════════════════════════════════════════════════
# § 7  SPEECH BUBBLES & MENUS
# ══════════════════════════════════════════════════════════════════════════════

def bubble_lines(text, tc, tr, accent=(180,148,222)):
    """Return list of positioned ANSI strings for a speech bubble."""
    if not text: return []
    ac = fg(*accent)
    tc_c = fg(240,234,255)
    bg_c = bg(32,24,50)
    wrapped = textwrap.wrap(text, 26)
    if not wrapped: return []
    iw = max(len(l) for l in wrapped)
    h  = len(wrapped) + 3
    sr = max(1, tr - h - 1)
    sc = max(1, tc - iw//2 - 1)
    out = []
    out.append(f'\033[{sr};{sc}H{ac}╭{"─"*(iw+2)}╮{RST}')
    for i,ln in enumerate(wrapped):
        pad = ' '*(iw-len(ln))
        out.append(f'\033[{sr+1+i};{sc}H{ac}│{RST}{bg_c}{tc_c} {ln}{pad} {RST}{ac}│{RST}')
    er = sr+1+len(wrapped)
    out.append(f'\033[{er};{sc}H{ac}╰{"─"*(iw+2)}╯{RST}')
    out.append(f'\033[{er+1};{sc+iw//2+1}H{ac}╲{RST}')
    return out


def menu_box(title, options, sel, tw):
    """Pixel-style old-school menu. Returns (lines_list, menu_row, menu_col)."""
    W = 36
    ac = fg(185,145,225)
    bg_c = bg(26,20,40)
    title_c = fg(255,218,100)
    opt_c = fg(220,218,240)
    sel_bg = bg(155,115,218)
    sel_c  = fg(255,255,255)
    dim_c  = fg(118,108,148)

    def pad(s, w):
        return (s[:w] + ' '*w)[:w]

    lines = []
    lines.append(f'{ac}╔{"═"*W}╗{RST}')
    t = pad(f' >> {title}', W)
    lines.append(f'{ac}║{bg_c}{title_c}{BOLD}{t}{RST}{ac}║{RST}')
    lines.append(f'{ac}╠{"═"*W}╣{RST}')
    for i,(key,label) in enumerate(options):
        if i == sel:
            row = pad(f'  ▶  {label}', W)
            lines.append(f'{ac}║{sel_bg}{sel_c}{row}{RST}{ac}║{RST}')
        else:
            row = pad(f'     {label}', W)
            lines.append(f'{ac}║{bg_c}{opt_c}{row}{RST}{ac}║{RST}')
    lines.append(f'{ac}╠{"═"*W}╣{RST}')
    lines.append(f'{ac}║{bg_c}{dim_c}{pad("  ↑↓ or click  ·  Enter/click=pick  ·  Esc=close", W)}{RST}{ac}║{RST}')
    lines.append(f'{ac}╚{"═"*W}╝{RST}')
    return lines


def name_box(cat_key, name_buf, tw, tr_center):
    d   = DEFS[cat_key]
    ac  = fg(185,145,225)
    bg_c= bg(26,20,40)
    ic  = fg(240,230,255)
    dc  = fg(178,158,218)
    blink = '█' if int(time.time()*2)%2==0 else ' '
    display = name_buf or d['label']
    W = 36
    sc = max(1, tw//2 - W//2)
    sr = tr_center - 2
    lines = [
        f'\033[{sr};{sc}H{ac}╭{"─"*W}╮{RST}',
        f'\033[{sr+1};{sc}H{ac}│{bg_c}{ic} Name your {fg(200,175,255)}{d["label"]}{ic} cat: {display[:20]}{blink}{"  "}{RST}{ac}│{RST}',
        f'\033[{sr+2};{sc}H{ac}│{bg_c}{dc} (Enter = confirm, blank = {d["label"][:18]}){RST}{ac}│{RST}',
        f'\033[{sr+3};{sc}H{ac}╰{"─"*W}╯{RST}',
    ]
    return lines

# ══════════════════════════════════════════════════════════════════════════════
# § 8  CAT AI  (state machine + wandering)
# ══════════════════════════════════════════════════════════════════════════════

_SPRITE_W_FULL = 16
_SPRITE_H_FULL = 16

def sprite_w():
    return _SPRITE_W_FULL // 2 if COMPACT else _SPRITE_W_FULL

def sprite_h():
    return _SPRITE_H_FULL // 2 if COMPACT else _SPRITE_H_FULL

# Backward-compat aliases used in rest-spot calculations (set in run())
SPRITE_W = _SPRITE_W_FULL
SPRITE_H = _SPRITE_H_FULL

class Cat:
    SIT='sit'; WALK='walk'; SLEEP='sleep'; LOAF='loaf'; HIDE='hide'

    def __init__(self, key, name, px, floor_py, cv_pw):
        self.key      = key
        self.name     = name
        self.d        = DEFS[key]
        self.sprites  = sprite_data.get_cat_sprites(key)
        self.px       = px
        self.py       = floor_py - sprite_h() + 4  # +4 compensates for transparent padding
        self.floor_py = floor_py
        self.cv_pw    = cv_pw
        self.dx       = random.choice([-1,1])
        self.state    = Cat.SIT
        self.frame    = 0
        self._frame_t = time.time()
        self._state_t = time.time() + random.uniform(3,8)
        # reminders
        self._water_t = time.time() + self.d['water_min']*60
        self._break_t = time.time() + self.d['break_min']*60
        self._motiv_t = time.time() + self.d['motiv_min']*60
        self._food_t  = time.time() + random.uniform(5, 15)*60  # first food check soon
        # bubble
        self.bubble   = f"Hi! I'm {name}! "
        self._bub_t   = time.time() + 5.0
        # special
        self.hidden   = False
        self._hide_t  = 0
        self.alive    = True
        # target-walking / rest-spot
        self.target_px    = None   # px to walk to
        self.target_py    = None   # py to settle at when arrived
        self.target_pose  = None   # state to enter when arrived
        self.claimed_spot = None   # index into scene.rest_spots, or None
        self._walk_fail_t = 0      # timestamp: give up walking if target unreachable
        # heart popup
        self.show_heart   = False
        self._heart_t     = 0
        # scene ref
        self._scene   = None

    def attach_scene(self, scene): self._scene = scene

    def say(self, text, dur=7.0):
        self.bubble  = text
        self._bub_t  = time.time() + dur

    def _msg(self, category):
        msgs = self.d['msg'].get(category, [])
        return random.choice(msgs) if msgs else ''

    def _release_spot(self):
        """Drop any claimed rest spot and return to floor level."""
        if self._scene and self.claimed_spot is not None:
            self._scene.release_spot(self)
            self.claimed_spot = None
            self.py = self.floor_py - sprite_h() + 4
        self.target_px = None
        self.target_py = None
        self.target_pose = None

    def _pick_state(self):
        # release any held spot first — cat is "moving on"
        self._release_spot()
        r = random.random()
        if r < 0.35:
            self.state = Cat.WALK
            self.dx = random.choice([-1,1])
            return
        # Try to claim a rest spot 60% of remaining → sit in bed / on tower / on keyboard (Mochi)
        if self._scene and r < 0.80:
            spot = self._scene.claim_spot(self)
            if spot:
                sp_px, sp_py, sp_pose, sp_idx = spot
                self.claimed_spot = sp_idx
                self.target_px    = sp_px
                self.target_py    = sp_py
                self.target_pose  = sp_pose
                self.state        = Cat.WALK
                self.dx           = 1 if sp_px > self.px else (-1 if sp_px < self.px else 1)
                self._walk_fail_t = time.time() + 20.0
                return
        # Fallback: just sit/loaf/sleep in place
        if   r < 0.88: self.state = Cat.SIT;   self.dx = 0
        elif r < 0.94: self.state = Cat.LOAF;  self.dx = 0
        else:          self.state = Cat.SLEEP; self.dx = 0

    def update(self):
        now = time.time()
        # animation frame
        rate = 0.22 if self.state == Cat.WALK else (2.0 if self.state == Cat.SLEEP else 1.5)
        if now - self._frame_t >= rate:
            self.frame += 1
            self._frame_t = now
        # clear bubble
        if self.bubble and now >= self._bub_t:
            self.bubble = None
        # clear heart
        if self.show_heart and now >= self._heart_t:
            self.show_heart = False
        # reminders (skip if bubble showing) — ring the terminal bell on wellness nudges
        if not self.bubble:
            if now >= self._water_t:
                self.say(self._msg('water'), 8); beep()
                self._water_t = now + self.d['water_min']*60
            elif now >= self._break_t:
                self.say(self._msg('stretch'), 8); beep()
                self._break_t = now + self.d['break_min']*60
            elif now >= self._motiv_t:
                self.say(self._msg('motiv'), 7)
                self._motiv_t = now + self.d['motiv_min']*60
            # Time-based food/snack reminders
            elif now >= self._food_t:
                hr = datetime.now().hour
                if hr in (7, 8, 12, 13, 18, 19):
                    m = self._msg('food_remind')
                    if m: self.say(m, 8); beep()
                elif 15 <= hr <= 17:
                    m = self._msg('snack_remind')
                    if m: self.say(m, 7); beep()
                self._food_t = now + 45*60  # check again in 45 min
        # special — Nyx hide/appear
        if self.key == 'nyx':
            if not self.hidden and random.random() < self.d.get('hide_chance',0):
                self.hidden = True
                self._hide_t = now + random.uniform(12, 35)
                self.say(self._msg('disappear'), 4)
            if self.hidden and now >= self._hide_t:
                self.hidden = False
                self.say(self._msg('appear'), 5)
        # special — Kulfi/Oreo knock plants
        for attr in ('knock_chance',):
            kc = self.d.get(attr, 0)
            if kc and random.random() < kc and self._scene:
                which = random.choice(['orchid','fern'])
                self._scene.knock(which)
                m = self._msg('knock')
                if m and not self.bubble:
                    self.say(m, 5)
        # special — Mochi/Oreo beg
        bc = self.d.get('beg_chance', 0)
        if bc and random.random() < bc and not self.bubble:
            cat = 'beg' if 'beg' in self.d['msg'] else 'attention_seek'
            m = self._msg(cat)
            if m: self.say(m, 6)
        # special — Saffron chirp
        cc = self.d.get('chirp_chance', 0)
        if cc and random.random() < cc and not self.bubble:
            m = self._msg('chirp')
            if m: self.say(m, 4)
        # state machine
        if now >= self._state_t:
            self._pick_state()
            self._state_t = now + random.uniform(3, 14)
        # movement
        if self.state == Cat.WALK:
            self.px += self.dx
            if self.target_px is not None:
                # Walking toward a rest spot: snap to pose when we arrive
                arrived = (
                    (self.dx > 0 and self.px >= self.target_px) or
                    (self.dx < 0 and self.px <= self.target_px) or
                    (self.dx == 0)
                )
                if arrived or now >= self._walk_fail_t:
                    if arrived:
                        self.px = self.target_px
                        self.py = self.target_py
                        self.state = self.target_pose or Cat.LOAF
                    else:
                        # Couldn't reach it in time — drop claim, resume wandering
                        self._release_spot()
                        self.state = Cat.SIT
                    self.dx = 0
                    self.target_px = None
                    self.target_py = None
                    self.target_pose = None
                    self._state_t = now + random.uniform(15, 35)
            else:
                lb = 22
                rb = self.cv_pw - sprite_w() - 4
                if self.px < lb: self.px = lb; self.dx = 1
                if self.px > rb: self.px = rb; self.dx = -1

    def sprite(self):
        if self.hidden:
            sp = sprite_data.get_nyx_eyes()
            return ds(sp, f'{self.key}_eyes') if sp else sp
        if self.state == Cat.WALK:
            k = 'walk_right' if self.dx >= 0 else 'walk_left'
        elif self.state == Cat.SLEEP:
            k = 'sleep_r'
        elif self.state == Cat.LOAF:
            k = 'sit2'
        else:
            k = 'sit'
        frames = self.sprites.get(k, self.sprites.get('sit', [[]]))
        frame = frames[self.frame % len(frames)] if frames else [[]]
        return ds(frame, f'{self.key}_{k}_{self.frame % max(1, len(frames))}')

    def hit(self, tc, tr):
        """Click hit test. tc/tr are 1-based terminal col/row."""
        cat_tc = self.px + 1
        cat_tr = self.py // 2 + 1
        sw, sh = sprite_w(), sprite_h()
        return (cat_tc <= tc <= cat_tc + sw and
                cat_tr  <= tr <= cat_tr  + sh // 2)

    def interact(self, action):
        msgs = self.d['msg']
        if action == 'pet':
            m = self._msg('pet')
            if self.key == 'hazel' and random.random() < self.d.get('flee_chance',0):
                self.say(self._msg('overwhelmed'), 5)
                time.sleep(0.05)
                self._release_spot()
                self.alive = False
                return
            self.show_heart = True
            self._heart_t = time.time() + 2.0
        elif action == 'cuddle':
            m = self._msg('cuddle') or self._msg('pet') or '...'
            self.show_heart = True
            self._heart_t = time.time() + 2.0
        elif action in msgs:
            m = self._msg(action)
        else:
            m = self._msg('food_love') or self._msg('eat') or '...'
        self.say(m or '...', 7)

# ══════════════════════════════════════════════════════════════════════════════
# § 9  SCENE STATE
# ══════════════════════════════════════════════════════════════════════════════

class Scene:
    def __init__(self, cv):
        self.cv   = cv
        pw, ph    = cv.pw, cv.ph
        self.floor_py   = ph - FLOOR_H * cv.scale

        def _fitx(x, w):
            """Clamp horizontal so a w-wide item still fits within canvas."""
            return max(2, min(x, pw - w - 2))

        def _fity(y, min_y=2):
            """Clamp vertical so items don't run off the top of the canvas."""
            return max(min_y, y)

        # Room sprite sizes (scaled if COMPACT)
        tower_w, tower_h = ds_size(*sprite_data.get_room_size('cattower_isolated'))
        desk_w, desk_h   = ds_size(*sprite_data.get_room_size('desk'))
        chair_w, chair_h = ds_size(*sprite_data.get_room_size('chair'))
        # lamp removed per user request
        shelf_w, shelf_h = ds_size(*sprite_data.get_room_size('shelf'))
        bed_w, bed_h     = ds_size(*sprite_data.get_room_size('catbed_isolated'))
        window_w, window_h = ds_size(*sprite_data.get_room_size('window'))
        bell_w, bell_h   = ds_size(*sprite_data.get_menu_icon_size('bell_clean'))
        sh = sprite_h()

        # Cat tower on the left, bottom sits on the floor line
        self.tower_px   = 2
        self.tower_py   = _fity(self.floor_py - tower_h, 2)

        # Desk in the middle-right area (4px transparent padding at bottom)
        self.desk_px    = _fitx(max(pw//2 - 10, tower_w + 8), desk_w)
        self.desk_py    = self.floor_py - desk_h + 4

        # Chair in front of desk (4px transparent padding at bottom)
        self.chair_px   = _fitx(self.desk_px + desk_w - 4, chair_w)
        self.chair_py   = self.floor_py - chair_h + 4

        # (lamp removed)

        # Shelf hanging on the wall above the desk
        self.shelf_px   = _fitx(self.desk_px + 2, shelf_w)
        self.shelf_py   = _fity(4, 2)

        # Window on the wall (left of shelf if space permits)
        self.window_px  = _fitx(max(tower_w + 6, 24), window_w)
        self.window_py  = _fity(2, 2)
        self.show_window = pw >= 110

        # Cat bed on the floor between tower and desk
        self.bed_px     = _fitx(max(tower_w + 6, pw//4), bed_w)
        self.bed_py     = self.floor_py - bed_h

        # Menu icons in the top-right corner: [BELL] [SAVE] [TRASH]
        trash_w, trash_h = ds_size(*sprite_data.get_menu_icon_size('trash_can'))
        save_w, save_h   = ds_size(*sprite_data.get_menu_icon_size('save_icon'))
        icon_gap = 3
        self.trash_w, self.trash_h = trash_w, trash_h
        self.save_w, self.save_h   = save_w, save_h
        self.bell_w, self.bell_h   = bell_w, bell_h

        self.trash_px   = _fitx(pw - trash_w - 4, trash_w)
        self.trash_py   = 2
        self.save_px    = _fitx(self.trash_px - save_w - icon_gap, save_w)
        self.save_py    = 2
        self.bell_px    = _fitx(self.save_px - bell_w - icon_gap, bell_w)
        self.bell_py    = 2

        # Plants (2 from sprite_data, knockable by Kulfi/Oreo)
        self.plants = DEFAULT_PLANTS[:2]
        plant1_w, plant1_h = ds_size(*sprite_data.get_plant_size(self.plants[0])) if self.plants else (8, 10)
        plant2_w, plant2_h = ds_size(*sprite_data.get_plant_size(self.plants[1])) if len(self.plants) > 1 else (8, 10)

        self.plant1_px  = _fitx(max(pw*3//4, pw - 40), plant1_w)
        self.plant1_py  = _fity(self.floor_py - plant1_h + 1, 2)

        self.plant2_px  = _fitx(max(pw*7//8, pw - 20), plant2_w)
        self.plant2_py  = _fity(self.floor_py - plant2_h + 1, 2)

        self.orchid_k   = False  # plant 1 knocked state
        self.fern_k     = False  # plant 2 knocked state

        # Mochi's keyboard gag — drawn only while occupied
        kb_w = 12 if COMPACT else 24
        self.keyboard_px = _fitx(max(pw//2 - 10, 40), kb_w)
        self.keyboard_py = self.floor_py - (4 if COMPACT else 8)

        # Apply any scene-position overrides from config file
        for field, val in (SCENE_OVERRIDES or {}).items():
            if hasattr(self, field) and isinstance(val, int):
                setattr(self, field, val)

        # ── Rest spots ──────────────────────────────────────────────────────
        # Cat sprites have 4px bottom + 3px top transparent padding (visible body ~9px).
        # py values place the sprite so the cat sits *inside* furniture, not on top.
        self.rest_spots = [
            # Cat bed — cats sleep curled inside the bed
            {'px': self.bed_px + 4,   'py': self.bed_py - sh + bed_h - 2,
             'pose': Cat.SLEEP, 'kind': 'bed',    'allowed': None},
            # Desk surface — cats loaf on desk (feet on desk top surface)
            {'px': self.desk_px + desk_w//2 - 4,  'py': self.desk_py - sh + 12,
             'pose': Cat.LOAF,  'kind': 'desk',   'allowed': None},
            # Tower top platform — sit regally
            {'px': self.tower_px + 1, 'py': self.tower_py - sh + 10,
             'pose': Cat.SIT,   'kind': 'tower',  'allowed': None},
            # Tower middle perch — loaf
            {'px': self.tower_px + 1, 'py': self.tower_py + tower_h//2 - sh + 8,
             'pose': Cat.LOAF,  'kind': 'tower',  'allowed': None},
            # Shelf — sit on the wall shelf
            {'px': self.shelf_px + 4, 'py': self.shelf_py + shelf_h - sh + 6,
             'pose': Cat.SIT,   'kind': 'shelf',  'allowed': None},
            # Mochi's keyboard gag — only Mochi may sit here
            {'px': self.keyboard_px + 3, 'py': self.keyboard_py - sh + 4,
             'pose': Cat.LOAF,  'kind': 'keyboard', 'allowed': {'mochi'}},
        ]
        self._occupants = {}   # spot_idx -> Cat

        # Click regions (term coords: col1,row1,col2,row2)
        self._bell_r    = None
        self._trash_r   = None
        self._save_r    = None
        self._plant1_r  = None
        self._plant2_r  = None

    # ── Rest spot API ───────────────────────────────────────────────────────

    def claim_spot(self, cat):
        """Reserve an unoccupied rest spot for `cat`. Returns (px,py,pose,idx) or None."""
        candidates = []
        for i, spot in enumerate(self.rest_spots):
            if i in self._occupants and self._occupants[i] is not cat:
                continue
            allowed = spot.get('allowed')
            if allowed is not None and cat.key not in allowed:
                continue
            candidates.append((i, spot))
        if not candidates:
            return None
        i, spot = random.choice(candidates)
        self._occupants[i] = cat
        return (spot['px'], spot['py'], spot['pose'], i)

    def release_spot(self, cat):
        for i, occ in list(self._occupants.items()):
            if occ is cat:
                del self._occupants[i]

    def _keyboard_occupied(self):
        for i, spot in enumerate(self.rest_spots):
            if spot.get('kind') == 'keyboard' and i in self._occupants:
                return True
        return False

    def knock(self, which):
        if which == 'orchid': self.orchid_k = True
        else:                 self.fern_k   = True

    def fix(self, which):
        if which == 'orchid': self.orchid_k = False
        else:                 self.fern_k   = False

    def _treg(self, px, py, w, h):
        return (px+1, py//2+1, px+w, (py+h)//2+1)

    def draw(self):
        cv = self.cv
        draw_background(cv)
        # Room sprites from sprite_data
        draw_sprite(cv, self.tower_px,  self.tower_py,  'cattower_isolated')
        draw_sprite(cv, self.desk_px,   self.desk_py,   'desk')
        draw_sprite(cv, self.chair_px,  self.chair_py,  'chair')
        draw_sprite(cv, self.shelf_px,  self.shelf_py,  'shelf')
        draw_sprite(cv, self.bed_px,    self.bed_py,    'catbed_isolated')
        if self.show_window:
            draw_sprite(cv, self.window_px, self.window_py, 'window')
        # Menu icons (top-right): bell, save, trash
        bell_sp = sprite_data.get_menu_icon('bell_clean')
        if bell_sp:
            bell_sp = ds(bell_sp, 'bell_icon')
            cv.blit(self.bell_py, self.bell_px, bell_sp)
        save_sp = sprite_data.get_menu_icon('save_icon')
        if save_sp:
            save_sp = ds(save_sp, 'save_icon')
            cv.blit(self.save_py, self.save_px, save_sp)
        trash_sp = sprite_data.get_menu_icon('trash_can')
        if trash_sp:
            trash_sp = ds(trash_sp, 'trash_icon')
            cv.blit(self.trash_py, self.trash_px, trash_sp)
        # Plants (knockable)
        if self.plants:
            draw_plant(cv, self.plant1_px, self.plant1_py, self.plants[0], self.orchid_k)
        if len(self.plants) > 1:
            draw_plant(cv, self.plant2_px, self.plant2_py, self.plants[1], self.fern_k)
        # Mochi's keyboard gag
        if self._keyboard_occupied():
            KB_FRAME = (28,  28,  36)
            KB_BODY  = (54,  54,  66)
            KB_KEY   = (186, 186, 200)
            KB_KEY_D = (138, 138, 156)
            KB_GAP   = (18,  18,  26)
            KB_BASE  = (82,  82,  96)
            kpx, kpy = self.keyboard_px, self.keyboard_py
            if COMPACT:
                # Compact keyboard: 12px wide x 4px tall
                cv.rect(kpy, kpx, 4, 12, KB_FRAME)
                cv.rect(kpy+1, kpx+1, 2, 10, KB_BODY)
                for cx in range(5):
                    cv.put(kpy+1, kpx+1+cx*2, KB_KEY)
                    cv.put(kpy+2, kpx+1+cx*2, KB_KEY_D)
                cv.rect(kpy+3, kpx+3, 1, 6, KB_BASE)
            else:
                cv.rect(kpy, kpx, 1, 24, KB_FRAME)
                cv.rect(kpy+7, kpx, 1, 24, KB_FRAME)
                cv.rect(kpy, kpx, 8, 1, KB_FRAME)
                cv.rect(kpy, kpx+23, 8, 1, KB_FRAME)
                cv.rect(kpy+1, kpx+1, 6, 22, KB_BODY)
                for ry in range(3):
                    for cx in range(11):
                        kx = kpx + 2 + cx*2
                        ky = kpy + 1 + ry*2
                        cv.put(ky, kx, KB_KEY)
                        cv.put(ky, kx+1, KB_GAP)
                        cv.put(ky+1, kx, KB_KEY_D)
                cv.rect(kpy+7, kpx+7, 1, 10, KB_BASE)
        # Click regions
        self._bell_r   = self._treg(self.bell_px,   self.bell_py,   self.bell_w,  self.bell_h)
        self._trash_r  = self._treg(self.trash_px,  self.trash_py,  self.trash_w, self.trash_h)
        self._save_r   = self._treg(self.save_px,   self.save_py,   self.save_w,  self.save_h)
        p1w, p1h = ds_size(*sprite_data.get_plant_size(self.plants[0])) if self.plants else (8, 10)
        p2w, p2h = ds_size(*sprite_data.get_plant_size(self.plants[1])) if len(self.plants) > 1 else (8, 10)
        self._plant1_r = self._treg(self.plant1_px, self.plant1_py, p1w, p1h)
        self._plant2_r = self._treg(self.plant2_px, self.plant2_py, p2w, p2h)

    def in_region(self, reg, tc, tr):
        if not reg: return False
        x1,y1,x2,y2 = reg
        return x1 <= tc <= x2 and y1 <= tr <= y2

    def in_bell(self,   tc, tr): return self.in_region(self._bell_r,   tc, tr)
    def in_trash(self,  tc, tr): return self.in_region(self._trash_r,  tc, tr)
    def in_save(self,   tc, tr): return self.in_region(self._save_r,   tc, tr)
    def in_orchid(self, tc, tr): return self.in_region(self._plant1_r, tc, tr)
    def in_fern(self,   tc, tr): return self.in_region(self._plant2_r, tc, tr)

# ══════════════════════════════════════════════════════════════════════════════
# § 10  MENU STATE MACHINE
# ══════════════════════════════════════════════════════════════════════════════

ACTION_OPTS = [
    ('dry',    '[DRY ] Dry food'),
    ('wet',    '[WET ] Wet food'),
    ('fish',   '[FISH] Fish'),
    ('yarn',   '[YARN] Ball of yarn'),
    ('toy',    '[TOY ] Feather toy'),
    ('pet',    '[PET ] Pet'),
    ('cuddle', '[HUG ] Cuddle'),
]
ACTION_KEYS = [k for k,_ in ACTION_OPTS]

class Menu:
    NONE='none'; BELL='bell'; ACTION='action'; NAME='name'; DISMISS='dismiss'

    def __init__(self):
        self.mode   = Menu.NONE
        self.sel    = 0
        self.unsumm = list(ALL_CAT_KEYS)
        self.pending_key = None   # cat key being summoned
        self.pending_cat = None   # Cat obj being interacted with
        self.name_buf    = ''
        self._active_cats = []    # for dismiss menu

    def open_bell(self, active):
        used = {c.key for c in active}
        self.unsumm = [k for k in ALL_CAT_KEYS if k not in used]
        if not self.unsumm: return False
        self.mode = Menu.BELL; self.sel = 0; return True

    def open_action(self, cat):
        self.mode = Menu.ACTION; self.pending_cat = cat; self.sel = 0

    def open_name(self, key):
        self.mode = Menu.NAME; self.pending_key = key; self.name_buf = ''

    def open_dismiss(self, active):
        if not active: return False
        self._active_cats = list(active)
        self.mode = Menu.DISMISS; self.sel = 0; return True

    def dismiss_opts(self):
        return [(c.key, c.name) for c in self._active_cats]

    def close(self):
        self.mode = Menu.NONE; self.pending_key = None
        self.pending_cat = None; self.name_buf = ''
        self._active_cats = []

    def bell_opts(self):
        return [(k, DEFS[k]["label"]) for k in self.unsumm]

# ══════════════════════════════════════════════════════════════════════════════
# § 11  MAIN LOOP
# ══════════════════════════════════════════════════════════════════════════════

def run_smoke_test():
    """Headless validation: exercise the full draw pipeline without a tty.

    Verifies: Canvas, Scene init + layout clamps, every cat sprite & update
    tick, speech bubble + menu rendering, rest-spot claim/release for every
    cat, Mochi-only keyboard gag, config.apply_config + DEFS mutation.
    Prints 'SMOKE TEST PASSED' on success; raises on failure.
    """
    errors = []
    def check(cond, msg):
        if not cond:
            errors.append(msg)
            print(f"  FAIL: {msg}")
        else:
            print(f"  ok:   {msg}")

    print("cozy-cats smoke test")

    # --- Canvas + Scene layout
    cv = Canvas(24, 120)
    scene = Scene(cv)
    check(cv.pw == 120 and cv.ph == 48, "Canvas 120x48 pixels")
    check(len(scene.rest_spots) >= 5,   f"scene has {len(scene.rest_spots)} rest spots")
    check(scene.tower_py >= 2,          "tower_py clamped (no top clipping)")
    check(scene.plant1_py >= 2,         "plant1_py clamped")
    check(scene.plant2_py >= 2,         "plant2_py clamped")

    # Narrow-terminal layout check
    cv2 = Canvas(24, 80)
    scene2 = Scene(cv2)
    bed_w, _ = sprite_data.get_room_size('catbed_isolated')
    desk_w, _ = sprite_data.get_room_size('desk')
    check(scene2.bed_px + bed_w < cv2.pw,  "narrow layout: bed fits")
    check(scene2.desk_px + desk_w < cv2.pw, "narrow layout: desk fits")

    # --- Render pipeline
    cv.fill()
    scene.draw()
    out1 = cv.render(start_row=1)
    check(len(out1) > 500, f"scene render produced {len(out1)} bytes")

    # --- Each cat instantiates, animates, renders
    for key in ALL_CAT_KEYS:
        c = Cat(key, DEFS[key]['label'], 50, scene.floor_py, cv.pw)
        c.attach_scene(scene)
        for _ in range(5):
            c.update()
        sp = c.sprite()
        check(sp is not None, f"cat {key}: sprite non-null")
        cv.blit(c.py, c.px, sp)

    # --- Rest spot claim/release
    test_cats = [Cat(k, DEFS[k]['label'], 50, scene.floor_py, cv.pw) for k in ALL_CAT_KEYS]
    for c in test_cats:
        c.attach_scene(scene)
    claimed = 0
    for c in test_cats:
        if scene.claim_spot(c) is not None:
            claimed += 1
    check(claimed >= 4, f"at least 4 generic rest spots claimable (got {claimed})")
    for c in test_cats:
        scene.release_spot(c)
    check(len(scene._occupants) == 0, "all spots released")

    # Keyboard spot: Mochi-only rule
    for c in test_cats:
        scene.release_spot(c)
    kb_spot_idx = next(i for i,s in enumerate(scene.rest_spots) if s['kind']=='keyboard')
    # Non-Mochi cats must NEVER land on the keyboard spot
    oreo_test = Cat('oreo', 'TestOreo', 50, scene.floor_py, cv.pw)
    oreo_test.attach_scene(scene)
    oreo_hit_kb = False
    for _ in range(300):
        spot = scene.claim_spot(oreo_test)
        if spot and spot[3] == kb_spot_idx:
            oreo_hit_kb = True
        scene.release_spot(oreo_test)
    check(not oreo_hit_kb, "non-Mochi cats cannot claim keyboard spot")
    # Mochi can eventually claim it
    mochi_test = Cat('mochi', 'TestMochi', 50, scene.floor_py, cv.pw)
    mochi_test.attach_scene(scene)
    mochi_got_kb = False
    for _ in range(300):
        spot = scene.claim_spot(mochi_test)
        if spot and spot[3] == kb_spot_idx:
            mochi_got_kb = True
        scene.release_spot(mochi_test)
    check(mochi_got_kb, "Mochi can claim the keyboard spot")
    # Occupied keyboard triggers draw_keyboard in scene.draw()
    scene.release_spot(mochi_test)
    scene._occupants[kb_spot_idx] = mochi_test
    check(scene._keyboard_occupied(), "keyboard occupancy detected")
    cv.fill(); scene.draw()  # must not crash with keyboard drawn
    scene._occupants.clear()

    # --- Speech bubble + menu
    lines = bubble_lines("Hello from the smoke test", 40, 10)
    check(len(lines) > 0, "speech bubble renders")
    m = menu_box("Test", [('a','Apple'),('b','Berry')], 0, 120)
    check(len(m) > 0, "menu_box renders")

    # --- Config apply
    cfg = {
        "sound": False,
        "cats": {
            "kulfi": {
                "water_min": 5,
                "messages": {"motiv": ["smoke-test message"]}
            }
        }
    }
    apply_config(cfg)
    check(SOUND_ON is False,                  "config: sound disabled")
    check(DEFS['kulfi']['water_min'] == 5,    "config: kulfi water_min updated")
    check("smoke-test message" in DEFS['kulfi']['msg']['motiv'],
          "config: kulfi custom motiv appended")

    # --- sprite_data integration
    cat_sprites = sprite_data.get_cat_sprites('seraphine')
    check('sit' in cat_sprites,               "sprite_data: seraphine has 'sit' anim")
    check('walk_right' in cat_sprites,        "sprite_data: seraphine has 'walk_right' anim")
    room_sp = sprite_data.get_room_sprite('desk')
    check(room_sp is not None,                "sprite_data: desk sprite loads")
    heart_sp = sprite_data.get_heart()
    check(heart_sp is not None,               "sprite_data: heart sprite loads")
    nyx_eyes = sprite_data.get_nyx_eyes()
    check(nyx_eyes is not None,               "sprite_data: nyx_eyes loads")

    # --- State save/load roundtrip (use temp file)
    global STATE_FILE
    import tempfile
    old_state_file = STATE_FILE
    with tempfile.TemporaryDirectory() as td:
        STATE_FILE = Path(td) / "state.json"
        save_state(test_cats[:3])
        loaded = load_state()
        check(len(loaded) == 3, f"state save/load roundtrip ({len(loaded)}/3)")
        check(loaded[0]['key'] in ALL_CAT_KEYS, "state entry has valid key")
        reset_state()
        check(not STATE_FILE.exists(), "reset_state deletes file")
    STATE_FILE = old_state_file

    # --- Compact mode (downscaled sprites for small panes, half-block fallback)
    global COMPACT, SPRITE_W, SPRITE_H
    old_compact = COMPACT
    COMPACT = True
    SPRITE_W = _SPRITE_W_FULL // 2
    SPRITE_H = _SPRITE_H_FULL // 2
    _ds_cache.clear()
    cv3 = Canvas(22, 120, scale=1)
    scene3 = Scene(cv3)
    cv3.fill()
    scene3.draw()
    c3 = Cat('kulfi', 'TestKulfi', 50, scene3.floor_py, cv3.pw)
    c3.attach_scene(scene3)
    sp3 = c3.sprite()
    check(sp3 is not None, "compact: cat sprite non-null")
    check(len(sp3) == 8,   f"compact: cat sprite height=8 (got {len(sp3)})")
    check(len(sp3[0]) == 8, f"compact: cat sprite width=8 (got {len(sp3[0])})")
    out3 = cv3.render(start_row=1)
    check(len(out3) > 500, f"compact: scene render produced {len(out3)} bytes")
    check(scene3.tower_py >= 2, "compact: tower fits in canvas")
    check(scene3.desk_py >= 0,  "compact: desk fits in canvas")
    COMPACT = old_compact
    SPRITE_W = _SPRITE_W_FULL
    SPRITE_H = _SPRITE_H_FULL
    _ds_cache.clear()

    # --- Kitty mode (scale=2, full-resolution sprites, higher pixel grid)
    cv4 = Canvas(22, 120, scale=2)
    scene4 = Scene(cv4)
    check(cv4.pw == 240 and cv4.ph == 88, f"kitty: canvas 240x88 (got {cv4.pw}x{cv4.ph})")
    expected_floor = 88 - FLOOR_H * 2
    check(scene4.floor_py == expected_floor, f"kitty: floor at row {scene4.floor_py} (expected {expected_floor})")
    cv4.fill()
    scene4.draw()
    c4 = Cat('seraphine', 'TestSera', 80, scene4.floor_py, cv4.pw)
    c4.attach_scene(scene4)
    sp4 = c4.sprite()
    check(sp4 is not None, "kitty: cat sprite non-null (full 16x16)")
    check(len(sp4) == 16,  f"kitty: cat sprite full height=16 (got {len(sp4)})")
    out4 = cv4.render_kitty(start_row=1)
    check(len(out4) > 500, f"kitty: render produced {len(out4)} bytes")
    check(scene4.tower_py >= 2,   "kitty: tower fits")
    check(scene4.desk_py >= 0,    "kitty: desk fits")
    check(scene4.chair_py >= 0,   "kitty: chair fits")

    print()
    if errors:
        print(f"SMOKE TEST FAILED ({len(errors)} errors)")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)
    else:
        print("SMOKE TEST PASSED")


def run():
    import argparse
    ap = argparse.ArgumentParser(description='cozy-cats — terminal cat colony')
    ap.add_argument('--height', type=int, default=0,
                    help='Override pane height in terminal rows')
    ap.add_argument('--no-sound',   action='store_true',
                    help='Disable terminal-bell sound on reminders')
    ap.add_argument('--no-restore', action='store_true',
                    help='Do not re-summon cats from last session')
    ap.add_argument('--reset-state', action='store_true',
                    help='Delete saved colony state before launching')
    ap.add_argument('--smoke-test',  action='store_true',
                    help='Headless render test: no tty, just verify draw pipeline')
    ap.add_argument('--no-kitty',    action='store_true',
                    help='Force half-block rendering even in Kitty terminal')
    args = ap.parse_args()

    # Load + apply config BEFORE we build DEFS-dependent things
    write_default_config()
    cfg = load_config()
    apply_config(cfg)

    global SOUND_ON
    if args.no_sound:
        SOUND_ON = False
    if args.reset_state:
        reset_state()

    if args.smoke_test:
        run_smoke_test()
        return

    th, tw = term_size()
    ph = args.height if args.height > 0 else th

    # Rendering mode: Kitty graphics (scale=2) or half-block fallback (scale=1)
    # Kitty mode doubles the pixel grid in both directions, giving 4x the
    # pixels in the same terminal space. Sprites render at full resolution.
    use_kitty = is_kitty() and not args.no_kitty
    scale = 2 if use_kitty else 1

    # Only use compact/downscaled mode for half-block on small panes
    global COMPACT, SPRITE_W, SPRITE_H
    if scale == 1 and ph <= 24:
        COMPACT = True
        SPRITE_W = _SPRITE_W_FULL // 2
        SPRITE_H = _SPRITE_H_FULL // 2
        _ds_cache.clear()

    cv    = Canvas(ph, tw, scale=scale)
    scene = Scene(cv)
    cats  : list[Cat] = []
    menu  = Menu()

    # If the user passed --height smaller than the terminal, dock the scene
    # to the bottom of the terminal instead of the top. row_offset shifts
    # every positioned write down by N rows; mouse clicks get the reverse
    # translation before being handed to canvas-local hit tests.
    row_offset = max(0, th - ph)

    # Restore previously-summoned colony
    if not args.no_restore:
        for entry in load_state()[:4]:
            key  = entry.get('key')
            name = entry.get('name') or (DEFS.get(key, {}).get('label') if key else None)
            if not key or key not in DEFS:
                continue
            spx = random.randint(30, max(31, cv.pw - 20))
            c = Cat(key, name, spx, scene.floor_py, cv.pw)
            c.attach_scene(scene)
            cats.append(c)

    # Require a real TTY — we use raw mode + mouse protocol, neither of which
    # work under subprocess pipes, Claude Code's `!` prefix, or bare `python -c`.
    try:
        old_settings = termios.tcgetattr(sys.stdin)
    except termios.error:
        sys.stderr.write(
            "\ncozy-cats needs a real interactive terminal (TTY).\n"
            "It can't run under a pipe, subprocess launcher, or Claude Code's\n"
            "`!` prefix — those don't forward stdin as a TTY.\n\n"
            "Open a fresh terminal window (kitty, iTerm2, Terminal.app) and run:\n"
            "  python3 " + os.path.abspath(__file__) + "\n\n"
            "Or if you've sourced the shell shortcut:\n"
            "  cozy-cats\n\n"
            "For a headless render test that needs no TTY, use --smoke-test.\n"
        )
        sys.exit(1)

    def cleanup(sig=None, _=None):
        try: termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)
        except: pass
        # Delete Kitty graphics image if we were using it
        kitty_del = '\033_Ga=d,i=1,q=2;\033\\' if use_kitty else ''
        sys.stdout.write(kitty_del + MOFF + SHOW + RST + '\033[2J\033[H')
        sys.stdout.flush()
        ac = fg(200,178,255)
        print(f'\n  {ac}Goodbye! Your cats miss you already~ {RST}\n')
        os._exit(0)

    signal.signal(signal.SIGINT,  cleanup)
    signal.signal(signal.SIGTERM, cleanup)

    try:
        tty.setraw(sys.stdin.fileno())
        sys.stdout.write(HIDE + MON)
        sys.stdout.flush()

        FPS    = CONFIGURED_FPS
        dt     = 1.0 / FPS
        last_f = 0.0
        prev_cat_count = len(cats)

        while True:
            now = time.time()

            # ── events ──────────────────────────────────────────────────────
            for evt in read_events():
                t = evt['t']

                if t == 'quit': cleanup()

                elif t == 'esc': menu.close()

                elif t == 'key':
                    k = evt['k']
                    if menu.mode in (Menu.BELL, Menu.ACTION, Menu.DISMISS):
                        if menu.mode == Menu.BELL:
                            opts_n = len(menu.unsumm)
                        elif menu.mode == Menu.ACTION:
                            opts_n = len(ACTION_OPTS)
                        else:
                            opts_n = len(menu._active_cats)
                        if k == 'UP':   menu.sel = (menu.sel-1) % opts_n
                        elif k == 'DOWN': menu.sel = (menu.sel+1) % opts_n
                        elif k == 'ENTER':
                            if menu.mode == Menu.BELL and menu.unsumm:
                                menu.open_name(menu.unsumm[menu.sel])
                            elif menu.mode == Menu.ACTION:
                                menu.pending_cat.interact(ACTION_KEYS[menu.sel])
                                menu.close()
                            elif menu.mode == Menu.DISMISS and menu._active_cats:
                                dismissed = menu._active_cats[menu.sel]
                                dismissed._release_spot()
                                dismissed.alive = False
                                menu.close()
                    elif menu.mode == Menu.NAME:
                        if k == 'ENTER':
                            name = menu.name_buf.strip() or DEFS[menu.pending_key]['label']
                            spx  = random.randint(30, max(31, cv.pw - 20))
                            c    = Cat(menu.pending_key, name, spx, scene.floor_py, cv.pw)
                            c.attach_scene(scene)
                            cats.append(c)
                            save_state(cats)
                            beep()
                            menu.close()
                        elif k == 'BACKSPACE':
                            menu.name_buf = menu.name_buf[:-1]
                        elif k not in ('UP','DOWN') and len(menu.name_buf) < 18:
                            menu.name_buf += k

                elif t == 'click':
                    tc = evt['col']
                    tr_raw = evt['row']
                    # Translate terminal click row into canvas-local row.
                    # Clicks above the docked scene are ignored (tr would be negative).
                    tr = tr_raw - row_offset
                    if tr < 1:
                        continue

                    # ── menu click ──────────────────────────────────────────
                    if menu.mode == Menu.BELL:
                        opts  = menu.bell_opts()
                        ml    = ph//2 - (len(opts)+6)//2
                        mc    = max(1, tw//2 - 19)
                        rel   = tr - ml - 2
                        if 0 <= rel < len(opts) and mc <= tc <= mc+38:
                            menu.sel = rel
                            menu.open_name(menu.unsumm[menu.sel])
                        elif tr < ml or tr > ml + len(opts) + 5:
                            menu.close()
                        continue

                    if menu.mode == Menu.ACTION:
                        ml  = ph//2 - (len(ACTION_OPTS)+6)//2
                        mc  = max(1, tw//2 - 19)
                        rel = tr - ml - 2
                        if 0 <= rel < len(ACTION_OPTS) and mc <= tc <= mc+38:
                            menu.sel = rel
                            menu.pending_cat.interact(ACTION_KEYS[menu.sel])
                            menu.close()
                        elif tr < ml or tr > ml + len(ACTION_OPTS) + 5:
                            menu.close()
                        continue

                    if menu.mode == Menu.DISMISS:
                        opts  = menu.dismiss_opts()
                        ml    = ph//2 - (len(opts)+6)//2
                        mc    = max(1, tw//2 - 19)
                        rel   = tr - ml - 2
                        if 0 <= rel < len(opts) and mc <= tc <= mc+38:
                            dismissed = menu._active_cats[rel]
                            dismissed._release_spot()
                            dismissed.alive = False
                            menu.close()
                        elif tr < ml or tr > ml + len(opts) + 5:
                            menu.close()
                        continue

                    if menu.mode == Menu.NAME:
                        menu.close(); continue

                    # ── scene clicks ────────────────────────────────────────
                    if scene.in_bell(tc, tr):
                        if len(cats) < 4:
                            menu.open_bell(cats)
                        continue

                    if scene.in_trash(tc, tr):
                        if cats:
                            menu.open_dismiss(cats)
                        continue

                    if scene.in_save(tc, tr):
                        save_state(cats)
                        # Brief confirmation via a temporary status message
                        for cat in cats:
                            if not cat.bubble:
                                cat.say("Saved!", 3)
                                break
                        continue

                    if scene.orchid_k and scene.in_orchid(tc, tr):
                        scene.fix('orchid'); continue
                    if scene.fern_k   and scene.in_fern(tc, tr):
                        scene.fix('fern');   continue

                    for cat in cats:
                        if cat.hit(tc, tr):
                            menu.open_action(cat); break

            # ── update cats ─────────────────────────────────────────────────
            for cat in cats:
                cat.update()
            cats = [c for c in cats if c.alive]
            if len(cats) != prev_cat_count:
                save_state(cats)
                prev_cat_count = len(cats)

            # ── render ──────────────────────────────────────────────────────
            if now - last_f < dt:
                time.sleep(0.01)
                continue
            last_f = now

            cv.fill()
            scene.draw()

            for cat in cats:
                sp = cat.sprite()
                py = cat.py if not cat.hidden else cat.py + 4
                cv.blit(py, cat.px, sp)
                # Heart popup above cat on pet/cuddle
                if cat.show_heart and not cat.hidden:
                    heart_sp = sprite_data.get_heart()
                    if heart_sp:
                        heart_sp = ds(heart_sp, 'heart')
                        cv.blit(py - 8, cat.px + sprite_w()//2 - 3, heart_sp)

            # When docked to the bottom, render draws into rows
            # (row_offset+1)..(row_offset+ph). Rows above stay as whatever
            # the shell had before — which is the intended dock behaviour.
            if use_kitty:
                out = [cv.render_kitty(start_row=1 + row_offset)]
            else:
                out = [cv.render(start_row=1 + row_offset)]

            # ── speech bubbles ───────────────────────────────────────────────
            for cat in cats:
                if cat.bubble and not cat.hidden:
                    tc = cat.px + sprite_w()//2 + 1
                    tr = cat.py//2 + 1 + row_offset
                    out.extend(bubble_lines(cat.bubble, tc, tr, (185,148,225)))

            # ── cat count ────────────────────────────────────────────────────
            cnt  = len(cats)

            # ── knocked-plant fix hints ──────────────────────────────────────
            hc = fg(255,200,80)
            if scene.orchid_k:
                ox = scene.plant1_px + 1
                oy = scene.plant1_py//2 + 1 + row_offset
                out.append(f'\033[{oy};{ox}H{hc}[click to fix plant]{RST}')
            if scene.fern_k:
                fx = scene.plant2_px + 1
                fy = scene.plant2_py//2 + 1 + row_offset
                out.append(f'\033[{fy};{fx}H{hc}[click to fix plant]{RST}')

            # ── menu overlays ────────────────────────────────────────────────
            if menu.mode == Menu.BELL:
                opts   = menu.bell_opts() or [('none','(all cats are here! max 4)')]
                mlines = menu_box('Summon a cat [BELL]', opts, menu.sel, tw)
                ml     = ph//2 - len(mlines)//2 + row_offset
                mc     = max(1, tw//2 - 19)
                for i,ln in enumerate(mlines):
                    out.append(f'\033[{ml+i};{mc}H{ln}')

            elif menu.mode == Menu.ACTION:
                cat_name = menu.pending_cat.name
                mlines   = menu_box(cat_name, ACTION_OPTS, menu.sel, tw)
                ml       = ph//2 - len(mlines)//2 + row_offset
                mc       = max(1, tw//2 - 19)
                for i,ln in enumerate(mlines):
                    out.append(f'\033[{ml+i};{mc}H{ln}')

            elif menu.mode == Menu.DISMISS:
                opts   = menu.dismiss_opts() or [('none','(no cats to dismiss)')]
                mlines = menu_box('Send away a cat', opts, menu.sel, tw)
                ml     = ph//2 - len(mlines)//2 + row_offset
                mc     = max(1, tw//2 - 19)
                for i,ln in enumerate(mlines):
                    out.append(f'\033[{ml+i};{mc}H{ln}')

            elif menu.mode == Menu.NAME:
                nlines = name_box(menu.pending_key, menu.name_buf, tw, ph//2 + row_offset)
                out.extend(nlines)

            # ── status bar ───────────────────────────────────────────────────
            hint = fg(95,82,125)
            hl   = fg(170,152,210)
            out.append(f'\033[{ph + row_offset};1H{hint}  {hl}BELL{hint}=summon  |  {hl}SAVE{hint}=save  |  {hl}DEL{hint}=dismiss  |  {hl}Ctrl+C{hint}=quit  |  {hl}{cnt}/4 cats{RST}')

            sys.stdout.write(''.join(out))
            sys.stdout.flush()

    except Exception as e:
        cleanup()
        raise


if __name__ == '__main__':
    run()
